ALTER TABLE venues
  ADD COLUMN region_code VARCHAR(8) NULL AFTER municipality,
  ADD KEY idx_venues_region_code (region_code);

-- El catálogo público está acotado a salas cuya ubicación en la RM fue verificada.
-- Las salas nuevas permanecen sin región y no se publican hasta ser clasificadas.
UPDATE venues
SET region_code = 'CL-RM'
WHERE
  municipality IN (
    'Alhué',
    'Buin',
    'Calera de Tango',
    'Cerrillos',
    'Cerro Navia',
    'Colina',
    'Conchalí',
    'Curacaví',
    'El Bosque',
    'El Monte',
    'Estación Central',
    'Huechuraba',
    'Independencia',
    'Isla de Maipo',
    'La Cisterna',
    'La Florida',
    'La Granja',
    'La Pintana',
    'La Reina',
    'Lampa',
    'Las Condes',
    'Lo Barnechea',
    'Lo Espejo',
    'Lo Prado',
    'Macul',
    'Maipú',
    'María Pinto',
    'Melipilla',
    'Ñuñoa',
    'Padre Hurtado',
    'Paine',
    'Pedro Aguirre Cerda',
    'Peñaflor',
    'Peñalolén',
    'Pirque',
    'Providencia',
    'Pudahuel',
    'Puente Alto',
    'Quilicura',
    'Quinta Normal',
    'Recoleta',
    'Renca',
    'San Bernardo',
    'San Joaquín',
    'San José de Maipo',
    'San Miguel',
    'San Pedro',
    'San Ramón',
    'Santiago',
    'Talagante',
    'Tiltil',
    'Vitacura'
  )
  OR canonical_name IN (
    'auditorio-municipal-de-maipu',
    'campus-el-claustro-u-mayor',
    'campus-el-claustro-universidad-mayor',
    'casa-de-la-cultura',
    'centro-arte-alameda',
    'centro-arte-alameda-sala-ceina',
    'centro-de-extension-alameda-sala-de-cine-uc',
    'duoc-uc-sede-padre-alonso-de-ovalle-santiago',
    'duoc-uc-sede-san-bernardo-san-bernardo',
    'duoc-uc-antonio-varas-providencia',
    'duoc-uc-sede-alameda-santiago',
    'el-biografo',
    'fundacion-centro-de-cine-y-creacion',
    'matucana-100',
    'sala-nemesio'
  );
